import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm test -- --coverage` (vitest html reporter).
    "coverage/**",
    // Local Codex app worktrees can contain their own .next output under
    // the repo root; linting generated files there makes `npm run lint`
    // slow and noisy.
    ".claude/**",
  ]),
]);

export default eslintConfig;
